/* Copyright (C) 2013 Interactive Brokers LLC. All rights reserved.  This code is subject to the terms
 * and conditions of the IB API Non-Commercial License or the IB API Commercial License, as applicable. */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;

namespace IBApi
{
    /**
     * @class CommissionReport
     * @brief class representing the commissions generated by an execution.
     * @sa Execution
     */
    public class CommissionReport
    {
        private string execId;
        private decimal commission;
        private string currency;
        private decimal realizedPNL;
        private decimal yield;
        private int yieldRedemptionDate;

        /**
        * @brief the execution's id this commission belongs to.
        */
        public string ExecId
        {
            get { return execId; }
            set { execId = value; }
        }

        /**
         * @brief the commissions cost.
         */
        public decimal Commission
        {
            get { return commission; }
            set { commission = value; }
        }

        /**
        * @brief the reporting currency.
        */
        public string Currency
        {
            get { return currency; }
            set { currency = value; }
        }

        /**
        * @brief the realised profit and loss
        */
        public decimal RealizedPNL
        {
            get { return realizedPNL; }
            set { realizedPNL = value; }
        }

        /**
         * @brief The income return.
         */
        public decimal Yield
        {
            get { return yield; }
            set { yield = value; }
        }

        /**
         * @brief date expressed in yyyymmdd format.
         */
        public int YieldRedemptionDate
        {
            get { return yieldRedemptionDate; }
            set { yieldRedemptionDate = value; }
        }

        public CommissionReport()
        {
            commission = 0m;
            realizedPNL = 0m;
            yield = 0m;
            yieldRedemptionDate = 0;
        }

        public override bool Equals(Object p_other)
        {
            bool l_bRetVal = false;

            if (p_other == null)
            {
                l_bRetVal = false;
            }
            else if (this == p_other)
            {
                l_bRetVal = true;
            }
            else
            {
                CommissionReport l_theOther = (CommissionReport)p_other;
                l_bRetVal = ExecId.Equals(l_theOther.ExecId);
            }
            return l_bRetVal;
        }
    }
}
